# Generated by Django 4.1.5 on 2023-03-07 11:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pos_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='card_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pos_api.cardholder', to_field='card_id'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='reader_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pos_api.merchant', to_field='reader_id'),
        ),
    ]
