# Generated by Django 4.1.5 on 2023-04-18 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='card_id',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='qr_code',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='card_id',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='cardholder_alias',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='merchant_alias',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='qr_code',
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
