# Generated by Django 4.1.5 on 2023-04-19 06:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pos_api', '0002_alter_payment_card_id_alter_payment_qr_code_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='message',
        ),
        migrations.AddField(
            model_name='administrator',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='merchant',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='administrator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pos_api.administrator'),
        ),
        migrations.AlterField(
            model_name='administrator',
            name='phone',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='manager',
            name='phone',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
