# Generated by Django 4.1.5 on 2023-04-19 08:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pos_api', '0003_remove_transaction_message_administrator_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardholder',
            name='administrator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pos_api.administrator'),
        ),
        migrations.AddField(
            model_name='merchant',
            name='administrator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pos_api.administrator'),
        ),
    ]
