# Generated by Django 4.1.5 on 2023-04-19 09:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pos_api', '0004_cardholder_administrator_merchant_administrator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardholder',
            name='administrator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pos_api.administrator', verbose_name='Created_by'),
        ),
    ]
